spring:
  config:
    import: optional:file:.env
  application:
    name: cloud-storage
  datasource:
    url: jdbc:postgresql://${HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  flyway:
    schemas:
      - public
      - user_management
  docker:
    compose:
      enabled: true
      file: ./compose.yml
      lifecycle-management: start-only   # или start-and-stop
      start:
        command: up
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: true
    show-sql: true
  data:
    redis:
      host: ${HOST}
      password: ${REDIS_PASSWORD}
      port: 6379
      database: 0
      username: ${REDIS_USER}
  session:
    redis:
      flush-mode: immediate
      namespace: spring:session
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
  jackson:
    default-property-inclusion: non_null
server:
  port: 8080
  servlet:
    session:
      timeout: 30m
    context-path: /api
  tomcat:
    max-part-count: 500
logging:
  level:
    org.springframework.session: TRACE
    org.springframework.data.redis: TRACE
    org.springframework.security: TRACE
    org.springframework.web: DEBUG
    com.github.ar4ik4ik.cloudstorage: DEBUG
minio:
  url: http://localhost:9000
  accessKey: cloud-storage-application
  secretKey: cloud-storage-application
  bucket: user-files
springdoc:
  paths-to-match:
    - /user/**
    - /resource/**
    - /directory/**
    - /auth/**
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    url: "/v3/api-docs"
  api-docs:
    path: /v3/api-docs
management:
  endpoints:
    web:
      exposure:
        include: info